//
//  Log.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Log: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _userId: String?
    @objc var _farmAddress: String?
    @objc var _farmId: String?
    @objc var _farmName: String?
    @objc var _searchDate: String?
    @objc var _spawningDate: String?
    
    class func dynamoDBTableName() -> String {

        return "eggy-mobilehub-1320062113-log"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_farmAddress" : "farmAddress",
               "_farmId" : "farmId",
               "_farmName" : "farmName",
               "_searchDate" : "searchDate",
               "_spawningDate" : "spawningDate",
        ]
    }
}
