//
//  NewEggy.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class NewEggy: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _number: String?
    @objc var _address: String?
    @objc var _name: String?
    @objc var _owner: String?
    
    class func dynamoDBTableName() -> String {

        return "eggy-mobilehub-1320062113-newEggy"
    }
    
    class func hashKeyAttribute() -> String {

        return "_number"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_number" : "number",
               "_address" : "address",
               "_name" : "name",
               "_owner" : "owner",
        ]
    }
}
